export default {
    ACTUALIZARINPUT: 'ACTUALIZAR_INPUT',
    //Login-------------------------------
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    SET_LOADER: 'SET_LOADER',
    //Registry
    REGISTER_ERROR: 'REGISTER_ERROR',
    SET_LOADER_REGISTRY: 'SET_LOADER_REGISTRY',
    //Password recovery
    PASSWORD_RECOVERY: 'PASSWORD_RECOVERY',
    PASSWORD_ERROR: 'PASSWORD_ERROR',
};