export default {
  ACTUALIZARINPUT: 'ACTUALIZAR_INPUT',
  // Login-------------------------------
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  SET_LOADER: 'SET_LOADER',
  // Registry
  REGISTER_ERROR: 'REGISTER_ERROR',
  SET_LOADER_REGISTRY: 'SET_LOADER_REGISTRY',
  // Password recovery
  PASSWORD_RECOVERY: 'PASSWORD_RECOVERY',
  PASSWORD_ERROR: 'PASSWORD_ERROR',
  // Profile picture
  USER_UPDATE_IMAGEN_URL: 'USER_UPDATE_IMAGEN_URL',
  USER_UPDATE_IMAGEN_ERROR: 'USER_UPDATE_IMAGEN_ERROR',
  SHOW_MODAL_PROFILE: 'SHOW_MODAL_PROFILE',
  HIDE_MODAL_PROFILE: 'HIDE_MODAL_PROFILE',
  // New post
  UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
  UPDATE_POST_ERROR: 'UPDATE_POST_ERROR',
  UPDATE_PHOTO_SUCCESS: 'UPDATE_PHOTO_SUCCESS',
  UPDATE_PHOTO_ERROR: 'UPDATE_PHOTO_ERROR',
  UPDATE_VIDEO_SUCCESS: 'UPDATE_VIDEO_SUCCESS',
  UPDATE_VIDEO_ERROR: 'UPDATE_VIDEO_ERROR',
  UPDATE_AUDIO_SUCCESS: 'UPDATE_AUDIO_SUCCESS',
  UPDATE_AUDIO_ERROR: 'UPDATE_AUDIO_ERROR',
  UPDATE_LOADER_POST: 'UPDATE_LOADER_POST',
  CLEAN_POST: 'CLEAN_POST',
  UPLOAD_YOUTUBE_LINK: 'UPLOAD_YOUTUBE_LINK',
  // Profile
  SET_LOADER_PROFILE: 'SET_LOADER_PROFILE',
  USER_FETCH_FAILED: 'USER_FETCH_FAILED',
  USER_FETCH_DBASE: 'USER_FETCH_DBASE',
  USER_UPDATE_COVER_URL: 'USER_UPDATE_COVER_URL',
  UPDATE_DESCRIPTION_PROFILE: 'UPDATE_DESCRIPTION_PROFILE',
  USER_DB_UPDATE: 'USER_DB_UPDATE',
  SET_DATA_CHANGE: 'SET_DATA_CHANGE',
  // Settings
  SIGN_OUT: 'SIGN_OUT',
  SIGN_OUT_ERROR: 'SIGN_OUT_ERROR',
  // Feed
  USER_UPLOAD_STORY: 'USER_UPLOAD_STORY',
  USER_UPLOAD_STORY_ERROR: 'USER_UPLOAD_STORY_ERROR',
  GET_STORIES: 'GET_STORIES',
  GET_STORIES_ERROR: 'GET_STORIES_ERROR',
  // Friends
  DATA_SEARCH: 'DATA_SEARCH',
  SEARCH_ERROR: 'SEARCH_ERROR',
  CLEAN_SEARCH: 'CLEAN_SEARCH',
};
